name: "deploy-will-fail-if-not-test"

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "any string"
        required: true
        type: string

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.ref_name != 'test'
        run: |
          echo "ERROR: You can only merge to prod from 'test'. You tried to merge from: ${{github.ref_name}}"
          exit 1
  echo_message:
    needs:
      check_branch
    runs-on: ubuntu-latest
    steps:
      - name: Print anything
        run: |
          echo "passed!"
          exit 0